controllers:
    resource: ../src/Controller/
    type: attribute


# === BACK END ROUTES ===
# These are any routes that use the /api path

apiSearchClasses:
    path: /api/searchTerms
    controller: App\Controller\APIController::searchTerms







# === FRONT END ROUTES ===

# Routes for annotator and directly related pages

termsSearch:
    path: terms-search
    controller: App\Controller\AnnotatorController::termsSearch



# Routes for other pages

readme:
    path: /readme
    controller: App\Controller\MiscController::readme
