controllers:
    resource: ../src/Controller/
    type: attribute



# === BACK END ROUTES ===
# These are any routes that use the /api path

apiGetTerm:
    path: /api/getTerm
    controller: App\Controller\APIController::getTerm


apiSearchClasses:
    path: /api/searchTerms
    controller: App\Controller\APIController::searchTerms


apiGetObjectProperty:
    path: /api/getObjectProperty
    controller: App\Controller\APIController::getObjectProperty




apiLoadOntology:
    path: /api/loadOntology
    controller: App\Controller\APIController::loadOntology


apiSaveResource:
    path: /api/saveResource
    controller: App\Controller\APIController::saveResource


# === FRONT END ROUTES ===

root:
    path: /
    controller: App\Controller\MiscController::home


# Routes for annotator and directly related pages

annotator:
    path: /annotator
    controller: App\Controller\AnnotatorController::annotator

termsSearch:
    path: terms-search
    controller: App\Controller\AnnotatorController::termsSearch



# Routes for other pages

readme:
    path: /readme
    controller: App\Controller\MiscController::readme


serverinfo:
    path: /server-info
    controller: App\Controller\MiscController::serverInfo