controllers:
    resource: ../src/Controller/
    type: attribute



# === BACK END ROUTES ===
# These are any routes that use the /api path

apiGetTerm:
    path: /api/getTerm
    controller: App\Controller\APIController::getTerm


apiSearchClasses:
    path: /api/searchTerms
    controller: App\Controller\APIController::searchTerms


apiLoadOntology:
    path: /api/loadOntology
    controller: App\Controller\APIController::loadOntology


apiCreateResource:
    path: /api/createResource
    controller: App\Controller\APIController::createResource

apiSaveResource:
    path: /api/saveResource
    controller: App\Controller\APIController::saveResource


apiGetResource:
    path: /api/getResource
    controller: App\Controller\APIController::getResource


apiExportAnnotations:
    path: /api/exportAnnotations
    controller: App\Controller\APIController::exportAnnotations



apiGetOntologyResources:
    path: /api/getOntologyResources
    controller: App\Controller\APIController::getOntologyResources 


apiDeleteResource:
    path: /api/deleteResource
    controller: App\Controller\APIController::deleteResource


apiAddResourceTerm:
    path: /api/addResourceTerm
    controller: App\Controller\APIController::addResourceTerm

apiRemoveResourceTerm:
    path: /api/removeResourceTerm
    controller: App\Controller\APIController::removeResourceTerm


# === FRONT END ROUTES ===

root:
    path: /
    controller: App\Controller\MiscController::home


# Routes for other pages

readme:
    path: /readme
    controller: App\Controller\MiscController::readme


serverinfo:
    path: /server-info
    controller: App\Controller\MiscController::serverInfo