# Prints the help instructions for the annotator.sh script

echo "annotator.sh Help"
echo "Usage: sh annotator.sh <command>"
echo ""
echo " - install"
echo "Create the volumes and containers for the annotator and start the web server and database"
echo ""
echo " - update"
echo "Update the source of the annotator from the working copy on the host machine"
echo "This also generates new documentation accessible at /docs."
echo ""
echo " - uninstall"
echo "Uninstalls the annotator from the host machine."
echo "This deletes the containers and the volumes."
echo ""
echo " - docs"
echo "Generate new documentation using phpdoc and jsdoc, accessible at /docs"

echo ""
echo ""