controllers:
    resource: ../src/Controller/
    type: attribute



# === API ROUTES ===
# These are any routes that use the /api path

# User API Routes

apiUserCreate:
    path: /api/user/create
    controller: App\Controller\UserAPIController::create

apiUserGetOntologies:
    path: /api/user/getOntologies
    controller: App\Controller\UserAPIController::getOntologies

apiUserDelete:
    path: /api/user/delete
    controller: App\Controller\UserAPIController::delete


# Ontology API Routes

apiOntologyLoad:
    path: /api/ontology/load
    controller: App\Controller\OntologyAPIController::load

apiOntologyGetDetails:
    path: /api/ontology/getDetails
    controller: App\Controller\OntologyAPIController::getDetails

apiOntologyGetResources:
    path: /api/ontology/getResources
    controller: App\Controller\OntologyAPIController::getResources 

apiOntologyDelete:
    path: /api/ontology/delete
    controller: App\Controller\OntologyAPIController::delete

apiOntologyExportAnnotations:
    path: /api/ontology/exportAnnotations
    controller: App\Controller\OntologyAPIController::exportAnnotations

# Terms API Routes

apiTermsSearch:
    path: /api/terms/search
    controller: App\Controller\TermsAPIController::search

apiTermsGet:
    path: /api/terms/get
    controller: App\Controller\TermsAPIController::get

# Resource API Routes

apiResourceCreate:
    path: /api/resource/create
    controller: App\Controller\ResourceAPIController::create

apiResourceSave:
    path: /api/resource/save
    controller: App\Controller\ResourceAPIController::save

apiResourceGet:
    path: /api/resource/get
    controller: App\Controller\ResourceAPIController::get

apiResourceDelete:
    path: /api/resource/delete
    controller: App\Controller\ResourceAPIController::delete

apiResourceAddTerm:
    path: /api/resource/addTerm
    controller: App\Controller\ResourceAPIController::addTerm

apiResourceRemoveTerm:
    path: /api/resource/removeTerm
    controller: App\Controller\ResourceAPIController::removeTerm



# === FRONT END ROUTES ===

root:
    path: /
    controller: App\Controller\MiscController::home


# Routes for other pages

readme:
    path: /readme
    controller: App\Controller\MiscController::readme


serverinfo:
    path: /server-info
    controller: App\Controller\MiscController::serverInfo


# Routes for Documentation

documentation:
    path: /docs
    controller: App\Controller\MiscController::documentation

# Route to give /docs/backend an endpoint
backenddocumentation:
    path: /docs/backend
    controller: App\Controller\MiscController::documentation

backendsrc:
    path: /docs/backend/src/{path}
    controller: App\Controller\DocumentationController::backendsrc
    requirements:
        path: .*

backendtest:
    path: /docs/backend/tests/{path}
    controller: App\Controller\DocumentationController::backendtests
    requirements:
        path: .*

frontend:
    path: /docs/frontend/{path}
    controller: App\Controller\DocumentationController::frontend
    requirements:
        path: .*