controllers:
    resource: ../src/Controller/
    type: attribute



# === BACK END ROUTES ===
# These are any routes that use the /api path


apiCreateUser:
    path: /api/createUser
    controller: App\Controller\APIController::createUser

apiGetUserOntologies:
    path: /api/getUserOntologies
    controller: App\Controller\APIController::getUserOntologies

apiDeleteUser:
    path: /api/deleteUser
    controller: App\Controller\APIController::deleteUser



apiGetTerm:
    path: /api/getTerm
    controller: App\Controller\APIController::getTerm


apiSearchClasses:
    path: /api/searchTerms
    controller: App\Controller\APIController::searchTerms


apiLoadOntology:
    path: /api/loadOntology
    controller: App\Controller\APIController::loadOntology


apiCreateResource:
    path: /api/createResource
    controller: App\Controller\APIController::createResource

apiSaveResource:
    path: /api/saveResource
    controller: App\Controller\APIController::saveResource


apiGetResource:
    path: /api/getResource
    controller: App\Controller\APIController::getResource


apiExportAnnotations:
    path: /api/exportAnnotations
    controller: App\Controller\APIController::exportAnnotations


apiDeleteOntology:
    path: /api/deleteOntology
    controller: App\Controller\APIController::deleteOntology


apiGetOntologyDetails:
    path: /api/getOntologyDetails
    controller: App\Controller\APIController::getOntologyDetails

apiGetOntologyResources:
    path: /api/getOntologyResources
    controller: App\Controller\APIController::getOntologyResources 


apiDeleteResource:
    path: /api/deleteResource
    controller: App\Controller\APIController::deleteResource


apiAddResourceTerm:
    path: /api/addResourceTerm
    controller: App\Controller\APIController::addResourceTerm

apiRemoveResourceTerm:
    path: /api/removeResourceTerm
    controller: App\Controller\APIController::removeResourceTerm


# === FRONT END ROUTES ===

root:
    path: /
    controller: App\Controller\MiscController::home


# Routes for other pages

readme:
    path: /readme
    controller: App\Controller\MiscController::readme


serverinfo:
    path: /server-info
    controller: App\Controller\MiscController::serverInfo


# Routes for Documentation

documentation:
    path: /docs
    controller: App\Controller\MiscController::documentation

# Route to give /docs/backend an endpoint
backenddocumentation:
    path: /docs/backend
    controller: App\Controller\MiscController::documentation

backendsrc:
    path: /docs/backend/src/{path}
    controller: App\Controller\DocumentationController::backendsrc
    requirements:
        path: .*

backendtest:
    path: /docs/backend/tests/{path}
    controller: App\Controller\DocumentationController::backendtests
    requirements:
        path: .*

frontend:
    path: /docs/frontend/{path}
    controller: App\Controller\DocumentationController::frontend
    requirements:
        path: .*